=================<br />
MODULE - OLIVIER<br />
=================<br />
<div style="float:left; margin-right:40px;">
<h2>1- Ajout de contact</h2>
<form action="" method="post">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
  <fieldset>
    <ul>
     <li>
       <label for="nom">Nom</label>
       <input type="text" id="nom" name="nom" />
     </li>
     <li>
         <label for="prenom ">Prenom</label>
         <input type="text" id="prenom" name="prenom" />
     </li>
     <li>
        <label for="nom">Telephone</label>
        <input type="text" id="telephone" name="telephone" />
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>
<br /><br />
<?php $this->saveAnnuaire(); ?>
</div>

<h2>2- Suppression de contact</h2>
<form action="" method="post">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
  <fieldset>
	<b><?php echo $this->supprimerAnnuaire(); ?></b>
	<input type="submit" value="Delete" />
  </fieldset>
</form>